language: node_js
test:
  adapter: postgresql
  database: travis_ci_
os: linux
node_js:
  - 'stable'
install: npm install
cache:
  directories:
    - 'node_modules'
script:
  - npm run test:coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
