version: 2.1
jobs:
  simple_build:
    docker:
      - image: circleci/node:13-browsers
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -al
      - checkout
      - run:
          name: Freestyling here only
          command: |
            echo free me jhorr
            echo $CIRCLE_USERNAME 
      - run:
          name: The Second step fattylee
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -al
            node -v
            git --version
  fix_build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: nothing serious
          command: |
            echo 'Gappy cofinf'
            echo 'This is the delivery pipeline'
            ls -al

workflows:
  version: 2
  my_custom_workflow_next:
    jobs:
      - simple_build
      - fix_build
