version: 2.1
jobs:
  test_build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second step fattylee
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -al
            git --version
            node -v
